name: main branch updated

on:
  push:
    branches:
      - main

jobs:
  publish-github-page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@main

      - name: Set up Python 3.9
        uses: actions/setup-python@main
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv invoke
          inv init-dev

      - name: Build docs
        run: |
          inv doc-build

      - name: Push documentation to Github Page
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
